name: Publish release
on:
  repository_dispatch:
    types: [monal_release]
  workflow_dispatch:
permissions: {}
jobs:
  promoteDraftRelease:
    name: Promote draft release to live release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Promote draft release to live release
        run: |
          echo "ID: ${{ needs.extractChangelog.outputs.release-id }}"
          echo "Repo: ${{ github.repository }}"
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/matthewrfennell/Monal/releases/195737383" \
            -d '{"draft": false, "prerelease": false, "make_latest": true}'
