# build a new stable release and push it to apple
name: stable.build-push

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
    branches: [ stable ]

  workflow_dispatch:

permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndPublishStable:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      APP_NAME: "Monal"
      BUILD_SCHEME: "Monal"
      APP_DIR: "Monal.app"
      BUILD_TYPE: "AppStore"
      EXPORT_OPTIONS_CATALYST_APPSTORE: "../scripts/exportOptions/Stable_Catalyst_ExportOptions.plist"
      EXPORT_OPTIONS_CATALYST_APP_EXPORT: "../scripts/exportOptions/Beta_Catalyst_ExportOptions.plist"
      EXPORT_OPTIONS_IOS: "../scripts/exportOptions/Stable_iOS_ExportOptions.plist"
    permissions:
      actions: write # needed to upload artifacts
      contents: write # needed for git push
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: true
          fetch-depth: 100
          fetch-tags: true
          show-progress: true
          lfs: true
      - name: Checkout submodules
        run: git submodule update -f --init --remote
      - run: |
          mkdir -p Monal/build/ipa Monal/build/app
          touch Monal/build/ipa/Monal.ipa
          touch Monal/build/app/Monal.zip
          touch Monal/build/app/Monal.pkg
      - uses: actions/upload-artifact@v4
        with:
          name: monal-ios
          path: Monal/build/ipa/Monal.ipa
          if-no-files-found: error
      - name: push tag to stable repo
        run: |
          git push origin Build_iOS_test1
      - uses: actions/upload-artifact@v4
        with:
          name: monal-catalyst-zip
          path: Monal/build/app/Monal.zip
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: monal-catalyst-pkg
          path: Monal/build/app/Monal.pkg
          if-no-files-found: error
